# The variables block similar to below is generated by the program and pasted into here

#export TITLE="Solr X.Y.Z"
#export SOURCE_PATH=path1:path2:path3
#export SOURCE_PACKAGES=package1:package2:package3
#export GROUP_MAPS="-group name1 package1:package2 -group name2 package3:package4"


# The next variable is script-specific
export OUTPUT_PATH=test-output/solr-combined

rm -rf  $OUTPUT_PATH
mkdir -p $OUTPUT_PATH

javadoc -d $OUTPUT_PATH -windowtitle "$TITLE" -sourcepath $SOURCE_PATH -subpackages $SOURCE_PACKAGES  $GROUP_MAPS\
    -notimestamp -nodeprecatedlist -noindex -nohelp \
    2>&1 |tee $OUTPUT_PATH/_javadoc.log
